version: "3.9"
services:
  llm-api:
    build: .
    container_name: llm-api
    ports:
      - "8888:8000"
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  web-ui:
    build: .
    container_name: llm-web
    ports:
      - "8501:8501"
    command: streamlit run web_ui.py --server.port=8501